spring.application.name=UserServiceDec24

spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/userservicedec24
spring.datasource.username=userservicedec24user
#spring.datasource.password=${PRODUCT_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
